[project]
name = "template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adrest==3.3.2",
    "hydra-core==1.3.2",
    "matplotlib==3.10.8",
    "numpy==2.4.0",
    "omegaconf==2.3.0",
    "pytorch-lightning==2.6.0",
    "pyyaml==6.0.3",
    "requests==2.32.5",
    "torch==2.9.1",
    "torchvision==0.24.1",
    "wandb==0.23.1",
]
