_target_: src.lightning_modules.DummyModule

network:
  _target_: src.networks.DummyNetwork
  input_size: 10
  output_size: 1

loss_fn:
  _target_: src.losses.MSELoss

defaults:
  - /optimizer: adamw
  - /lr_scheduler: constant
