# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

modelcheckpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  save_top_k: 2
  filename: 'best'
  mode: 'min'
  save_last: true
  verbose: true
  save_on_exception: true