# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

modelcheckpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  dirpath: null
  filename: 'best'
  save_top_k: 1
  mode: 'min'
  save_last: true
  verbose: true