# @package _global_
project_name: ???
task_name: ???
continue_from_id: False
seed: 42
compile: True
phase: train

defaults:
  - trainer: ???
  - data: ???
  - model: ???
  - callbacks: ???
  - logger: ???
  - _self_